### ISSUE TITLE
Option to remove multiple comms at once

### ISSUE THREAD

**Issue by crashzk** [aXenDeveloper/sourcebans-web-theme-fluent#10]
Bans menu would have this option:
![image](https://user-images.githubusercontent.com/32937653/128248456-25fbe96b-d566-4010-8618-a822d84ce287.png)

![image](https://user-images.githubusercontent.com/32937653/128248406-9a95dc0b-72c5-4ff0-8e87-c8bddfd941a0.png)

Would it be possible to put these same options in the Comms part?
![image](https://user-images.githubusercontent.com/32937653/128248624-fa43653e-5fc5-494d-91fc-eaef7a9c6ed2.png)

**Comment by aXenDeveloper** [comment]
Currently, the sourcebans engine does not allow this feature to be added to the new code.
