### ISSUE TITLE
Implement Bans | Ban Submissions

### ISSUE THREAD

**Issue by crashzk** [aXenDeveloper/sourcebans-web-theme-fluent#12]
Would it be possible to implement an option to remove/delete all Ban Submissions Archive at once? Algo como tem para a lista de bans.
![image](https://user-images.githubusercontent.com/32937653/128274485-4b08ba6f-73e4-4139-a06a-1b8d605f9581.png)

Administrator only selects the ones he wants to delete and deletes several at once.

**Comment by aXenDeveloper** [comment]
Currently, the sourcebans engine does not allow this feature to be added to the new code.
