### ISSUE TITLE
BUG Intro Text option of Main Settings

### ISSUE THREAD

**Issue by crashzk** [aXenDeveloper/sourcebans-web-theme-fluent#13]
Option to add **Title & Text in Dashboard Settings** is buggy. I can't type anything in the Intro **Text option**.

![image](https://user-images.githubusercontent.com/32937653/128274969-2b4d97c0-8e2c-4009-bf43-3758b6a750ca.png)

I can't write anything.

**Comment by crashzk** [comment]
Note, official theme has option to edit text.
![image](https://user-images.githubusercontent.com/32937653/129497769-d80ca7ed-10d8-4e51-a66e-c398e2614e3d.png)

**Comment by crashzk** [comment]
Fixed with the latest commits, thanks.

**Comment by crashzk** [comment]
My suggestion now would be just that when you stay in the dark theme change the text editor background too.
![image](https://user-images.githubusercontent.com/32937653/130305148-545c9bd5-a9e7-4bd6-b2d6-5e5eda5f8684.png)

**Comment by aXenDeveloper** [comment]
I can't change background and text color in editor.
