### ISSUE TITLE
Improved Admin Management | Add New Admin

### ISSUE THREAD

**Issue by crashzk** [aXenDeveloper/sourcebans-web-theme-fluent#14]
Separate with some kind of block the servers from the server group, for example in the print so to speak.

![image](https://user-images.githubusercontent.com/32937653/128603810-8b320eb8-b221-44cb-8445-e70595c4c143.png)

**Comment by aXenDeveloper** [comment]
I can't reproduce this error. Where are these groups from?

**Comment by crashzk** [comment]
It would be when you are going to create a group, there is an option of administration group and server group.

After you create a server group whenever you add a new server in SourceBans just add the server to the group you created.

This is good to avoid having to place privileges on several servers one by one, I select the group and all servers that are in this group the player receives the privileges.

**Comment by crashzk** [comment]
Default theme of sourcebans, when you have these server groups, it shows as follows when I'm going to add new players in sourcebans.

![image](https://user-images.githubusercontent.com/32937653/130339445-8871f656-aab5-4ceb-b047-82ec8806c4b6.png)
