### ISSUE TITLE
Ban Submissions > Ban and ServerName Inst working

### ISSUE THREAD

**Issue by henriquemod** [aXenDeveloper/sourcebans-web-theme-fluent#2]
Button Ban inside Ban Submissions does nothing, the conversion of ServerID into server name isn't working too, it get stucked with the message "Retrieving Hostname" , in default template both woks just fine.

Tested in: 
Firefox 87.0
Chrome 89.0
Sourcebans++ 1.7.0

**Comment by aXenDeveloper** [comment]
> Button Ban inside Ban Submissions does nothing

Fixed

> the conversion of ServerID into server name isn't working too, it get stucked with the message "Retrieving Hostname" , in default template both woks just fine.

Where is this exactly?

**Comment by henriquemod** [comment]
![nameserver](https://user-images.githubusercontent.com/43145168/115795541-7a7f6500-a3a6-11eb-8ad2-4f224199e9be.png)

When you expand the submission, it loads and show the submission details except eh server name.
