### ISSUE TITLE
Add map image in servers tab

### ISSUE THREAD

**Issue by crashzk** [aXenDeveloper/sourcebans-web-theme-fluent#25]
Official theme of sourcebans when we click to see more information from the servers, where it shows the players, option to connect to the server also shows an image of the map.

![image](https://user-images.githubusercontent.com/32937653/131260486-be4213ae-a3b8-4c7c-9d0e-e072b4bdfd33.png)

It would be interesting to add this image of maps in the theme.

![image](https://user-images.githubusercontent.com/32937653/131260369-7008684e-2dfe-4e13-bebc-0638bea63943.png)

**Comment by aXenDeveloper** [comment]
This is a deliberate action.
