### ISSUE TITLE
Show Latest Players Blocked info

### ISSUE THREAD

**Issue by crashzk** [aXenDeveloper/sourcebans-web-theme-fluent#27]
When we click on the players in the Latest Players Blocked option, we click on the blocked players, it should open a popup showing to see the reason for the ban and so on.
![image](https://user-images.githubusercontent.com/32937653/131260651-b7a7b3fb-8d2f-4c11-8782-27e8b5f49bf9.png)

Something like:
![image](https://user-images.githubusercontent.com/32937653/131260728-3f7803e8-3431-477d-997f-e34e8cdee039.png)

**Comment by aXenDeveloper** [comment]
This is a deliberate action.
