### ISSUE TITLE
Issue: Warning: Smarty error: unable to read resource

### ISSUE THREAD

**Issue by SanjaySRocks** [aXenDeveloper/sourcebans-web-theme-fluent#28]
Error Log:

Warning: Smarty error: unable to read resource: "page_footer.tpl" in /var/www/html/bans/includes/smarty/Smarty.class.php on line 1100

**Comment by aXenDeveloper** [comment]
Are you using Sourcebans 1.7+?

**Comment by SanjaySRocks** [comment]
No the release version 1.6.3

**Comment by aXenDeveloper** [comment]
Minimum sourcebans version required is 1.7.+
