### ISSUE TITLE
Theme Error

### ISSUE THREAD

**Issue by IZOcC** [aXenDeveloper/sourcebans-web-theme-fluent#3]
Warning: Smarty error: unable to read resource: "page_footer.tpl" in /home/infinit3/public_html/sourcebans/sourcebans_public/includes/smarty/Smarty.class.php on line 1100

**Comment by aXenDeveloper** [comment]
Theme requires sourcenbsns version 1.7 or higher.
See: https://github.com/aXenDeveloper/sourcebans-web-theme-fluent#requirements-%EF%B8%8F

**Comment by aXenDeveloper** [comment]
Yes, in main repository.

**Comment by IZOcC** [comment]
I replaced the files with the ones from 1.7 and when I install it gives me the end,
Compose autoload not found! run `composer install` in the root directory of your sourcebans ++ installation.

**Comment by IZOcC** [comment]
https://sbans.infinityzone.ro/

**Comment by aXenDeveloper** [comment]
Use this: https://getcomposer.org/
If you have question please write in [issues sourcebans](https://github.com/sbpp/sourcebans-pp/issues).
