### ISSUE TITLE
Improved option to edit Bans

### ISSUE THREAD

**Issue by crashzk** [aXenDeveloper/sourcebans-web-theme-fluent#31]
Also separate the option to **save changes** and go **back** a little.

![image](https://user-images.githubusercontent.com/32937653/131753713-46c4e1ef-5a61-499b-82dc-7354618af2d3.png)

**Comment by crashzk** [comment]
Same thing in the option **Bans - Ban Protests**, when you will reply by email to the contact of the banned player.

![image](https://user-images.githubusercontent.com/32937653/131756481-fce36b50-f2a0-43df-851d-2f3411832574.png)

**Comment by Rushaway** [comment]
Fixed in https://github.com/aXenDeveloper/sourcebans-web-theme-fluent/pull/50
