### ISSUE TITLE
Editar Intro Text - 403 Forbidden

### ISSUE THREAD

**Issue by crashzk** [aXenDeveloper/sourcebans-web-theme-fluent#33]
Whenever I try to edit the **Intro Text** option it shows the error when I click to save the changes:
![image](https://user-images.githubusercontent.com/32937653/131754833-924d44b2-3272-45a0-a3d4-0fc9cb65a334.png)

From what I noticed is whenever I try to center the text, it doesn't go in the case, I click to save and the error occurs.

It is currently configured like this:
![image](https://user-images.githubusercontent.com/32937653/131754904-16bfe646-c485-41d1-8319-fae0bf7463df.png)

**Comment by crashzk** [comment]
I noticed that even if I try to configure texts with links to open in new windows it also gives an error.

**Comment by aXenDeveloper** [comment]
Is it the same on the default theme?

**Comment by crashzk** [comment]
> Is it the same on the default theme?

Worse than yes, I believe it's something in my hosting, right?

**Comment by crashzk** [comment]
I identified the error, it was Mod Security. I'll be seeing with my host's support to fix, thanks.
