### ISSUE TITLE
mysql database error editing bans

### ISSUE THREAD

**Issue by crashzk** [aXenDeveloper/sourcebans-web-theme-fluent#38]
There are times when I'm going to edit the bans in SourceBans and it shows the following error:
```
/home/zkservi/public_html/sourcebans/pages/admin.edit.ban.php
on line
198

Fatal error
: Uncaught Error: Cannot use object of type ADORecordSet_mysqli as array in /home/zkservi/public_html/sourcebans/pages/admin.edit.ban.php:198 Stack trace: #0 /home/zkservi/public_html/sourcebans/includes/page-builder.php(143): require_once() #1 /home/zkservi/public_html/sourcebans/index.php(29): build() #2 {main} thrown in
```
![image](https://user-images.githubusercontent.com/32937653/135950882-6757d83c-58e8-4baf-98dc-f8db2a8bea0b.png)

I've already checked the official sourcebans theme, and during testing, I edited several bans and at no time showed this error.

**Comment by aXenDeveloper** [comment]
Where are you in to edit the ban?

**Comment by crashzk** [comment]
You can disregard... Error occurs in the official theme as well: 
```
Fatal error: Uncaught Error: Cannot use object of type ADORecordSet_mysqli as array in /home/zkservi/public_html/sourcebans/pages/admin.edit.ban.php:198 Stack trace: #0 /home/zkservi/public_html/sourcebans/includes/page-builder.php(143): require_once() #1 /home/zkservi/public_html/sourcebans/index.php(29): build() #2 {main} thrown in /home/zkservi/public_html/sourcebans/pages/admin.edit.ban.php on line 198
```
![image](https://user-images.githubusercontent.com/32937653/136128778-8a391cc0-e424-400e-a1c4-92610a26167b.png)

Something in my hosting web, I'll be seeing.
