### ISSUE TITLE
Colorpicker

### ISSUE THREAD

**Issue by R100T** [aXenDeveloper/sourcebans-web-theme-fluent#4]
Niestety ale tryb nocny oraz colorpicker nie działa poprawnie, tak samo jak wysuwane menu na telefonie.

**Comment by aXenDeveloper** [comment]
Podaj link do strony.

**Comment by R100T** [comment]
Sb.go-dreams.pl

**Comment by aXenDeveloper** [comment]
Pliki JS mają status 404 (Nie istnieją).
![image](https://user-images.githubusercontent.com/58148176/119097482-1091c400-ba15-11eb-82d5-9b581067ac0b.png)

**Comment by R100T** [comment]
Pobrałem stąd i wrzuciłem wszystko tak jak powinno być.

**Comment by aXenDeveloper** [comment]
Na pewno masz folder o nazwie **sourcebans-web-theme-fluent**?

**Comment by R100T** [comment]
Tak miałem i sourcebans-Web-theme-fluent i sourcebans-Web-theme-fluent-1.0.2
![Uploading 5B1761EB-768D-4AD5-9DDB-CE722A3E06CC.jpeg…]()

**Comment by aXenDeveloper** [comment]
Usuń końcówkę **-1.0.2**

**Comment by R100T** [comment]
Dzięki bardzo 😅
