### ISSUE TITLE
Responsive Theme Bug

### ISSUE THREAD

**Issue by crashzk** [aXenDeveloper/sourcebans-web-theme-fluent#42]
I accessed sourcebans on my cell phone, this theme is bug, at least the part where it shows more information about banned players and comms.

My cell phone would be android, I don't know if it changes anything.

**Comment by crashzk** [comment]
List Bans
![image](https://user-images.githubusercontent.com/32937653/139587644-32799c21-c075-454c-a4c7-3365be4038f1.png)

List Comms
![image](https://user-images.githubusercontent.com/32937653/139587678-72ae143d-efbc-4133-ad06-652f20d4697a.png)

**Comment by Rushaway** [comment]
+ If you have the comments section enable. You aren't able to see anything on phone.

**Comment by Rushaway** [comment]
I made a temp fix in https://github.com/aXenDeveloper/sourcebans-web-theme-fluent/pull/50/commits/b6d40e8d9242148540c60a06b315d9eb3ab67b0a
By showing comms block & buttons only on Desktop version. 
But for me this is not the final fix. A better fix have to be made in the future. @aXenDeveloper
