### ISSUE TITLE
Server Rcon bug

### ISSUE THREAD

**Issue by ByKyTa** [aXenDeveloper/sourcebans-web-theme-fluent#43]
I have a bug sm plugins list. Can you help me fix it ?
![image](https://user-images.githubusercontent.com/33537916/139839717-ffe742b2-b247-47dc-8d7c-e0e1d02d5e7b.png)

**Comment by aXenDeveloper** [comment]
This is not a theme bug.
https://github.com/sbpp/sourcebans-pp/issues
