### ISSUE TITLE
Button problem

### ISSUE THREAD

**Issue by Ferks-FK** [aXenDeveloper/sourcebans-web-theme-fluent#44]
The button to change the theme to dark/light doesn't work, nothing happens when you click.

**Comment by aXenDeveloper** [comment]
Check console in browser

**Comment by Ferks-FK** [comment]
> Check console in browser

There is nothing, no mistake.

**Comment by aXenDeveloper** [comment]
Provide a link to your website.

**Comment by Ferks-FK** [comment]
> Provide a link to your website.

http://sb.redealok.net

**Comment by aXenDeveloper** [comment]
JavaScript isn't load in your website.

**Comment by Ferks-FK** [comment]
> JavaScript isn't load in your website.
What do you mean?
How to load?

**Comment by aXenDeveloper** [comment]
Ask your server administrator.

**Comment by Ferks-FK** [comment]
> 
I don't understand, I don't have an administrator, I just inslaid it on a Linux account.
It only happens with your theme.
