### ISSUE TITLE
BUG Block List Banned Players

### ISSUE THREAD

**Issue by crashzk** [aXenDeveloper/sourcebans-web-theme-fluent#47]
Blocklist of banned players has a BUG.

When the player tries to connect banned he is kicked and shows in sourcebans and shows how many times he tried too.

![image](https://user-images.githubusercontent.com/32937653/152623294-5ac9ac78-cd2a-4a6a-b8c9-8e4fd0afbb71.png)

As you can see in the print, comes his nick and a big space and **`,`** after that. I believe it should be closer to the **`,`** of the player's nick, correct?

**Comment by Rushaway** [comment]
Just replace the <span> balise by <i>
`{if $ban.banlog == ""}
                            <span class="text:italic">Never</span>
                          {else}
                            <i>{$ban.banlog}</i>
                          {/if}`

**Comment by crashzk** [comment]
> Just replace the span balise by i `{if $ban.banlog == ""} <span class="text:italic">Never</span> {else} <i>{$ban.banlog}</i> {/if}`

Worked, thank you!
