### ISSUE TITLE
Bug - ban details

### ISSUE THREAD

**Issue by Kacper44** [aXenDeveloper/sourcebans-web-theme-fluent#6]
When we click in ban details, we can see "Blocked" what means how much times the blocked player was trying to connect again and him nickname. If the number of connections is large the site begins to stretch.

Example: https://sourcebans.1s2k.pl/index.php?p=banlist&advSearch=STEAM_1:1:614586934&advType=steamid

**Comment by crashzk** [comment]
For me this is normal, including the link you sent to.

![image](https://user-images.githubusercontent.com/32937653/126725727-62b562ca-7203-441b-9a42-9daac4f480fe.png)
