### ISSUE TITLE
Cannot set dark mode

### ISSUE THREAD

**Issue by distratul** [aXenDeveloper/sourcebans-web-theme-fluent#7]
Hi. I cannot use the button to switch to dark mode and i cannot see the button to change the collor.
I use php 7.4 and the latest version of sourcebans ++
![Untitled](https://user-images.githubusercontent.com/33494107/127342295-68eb32bb-ec83-4220-b572-6e5af6e3ea12.png)

**Comment by aXenDeveloper** [comment]
Check path for javascript file.

**Comment by distratul** [comment]
Forgive me, but how can i do that? I am not a pro scripter...just a poor modifyer.

**Comment by distratul** [comment]
Ok. I updated not the theme and is working. Thanks for this beautifull theme. THE BEST.
